### PR TITLE
Feature/#14 require full path

### LINKED ISSUE #14: Don't require componentsPath
Default to CWD when no `componentsPath` is given

### PR DESCRIPTION
**Pull request by asbjornh**
Fixes #14 

Refactors all exported functions:
- Functions now expect a full path
  - `filePath` for `rename`, `to-stateful` and `to-stateless`
  - `folderPath` for `new` and  `page`
- Removes component path resolution (`get-component.js`)

Also some other things:
- Cleaned up folder structure in `test` folder
- Added tests for all exported functions and some utils.
- Refactored the debug functions because they were annoying.
- Removed `remove-last-slug` util because it turns out this is exactly what `path.dirname` does

### CODE REVIEW

**Comment by pellebjerkestrand** [comment]
What about not doing `cwd` here, but simplifying this component by letting it take a required path? `@creuna/cli` can then pass `cwd` if a path is not specified.

**Comment by asbjornh** [comment]
Yes!

**Comment by asbjornh** [comment]
Better now @pellebjerkestrand ? Or did you mean just accept a single file path?

If so, we'd have to do the following:
- `rename`, `to-stateful` and `to-stateless` should all accept a `filePath`
- Move `source/utils/get-component.js` (which resolves component path) to `cli.`
- `new-component` and `new-page` should accept a `folderPath`

I can't decide whether this is better or not. This complexity needs to live somewhere, but which place makes more sense?

**Comment by pellebjerkestrand** [comment]
Accepting a `filePath` and `folderPath` would be 💯.

**Comment by asbjornh** [comment]
@pellebjerkestrand 
Updated as described above. Good to merge? :)

**Pull request merged**
